name: Build And Test
on:
  push:
    branches:
      - main
      - develop
      - develop/**
      - feature/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: DotNet Build
        run: dotnet build --no-restore
      - name: DotNet Unit Test
        run:  dotnet test --no-restore
